//
//  AirportsAndAirlines.swift
//  UK FTL Calc
//
//  Created by Adam Da Costa on 03/08/2025.
//

import Foundation

// MARK: - Airport Data
struct AirportsAndAirlines {
    // Common airport codes with time zones
    static let airports: [(String, String, String)] = [
        ("LHR", "London Heathrow", "Europe/London"),
        ("LGW", "London Gatwick", "Europe/London"),
        ("STN", "London Stansted", "Europe/London"),
        ("JFK", "New York JFK", "America/New_York"),
        ("LAX", "Los Angeles", "America/Los_Angeles"),
        ("ORD", "Chicago O'Hare", "America/Chicago"),
        ("DFW", "Dallas/Fort Worth", "America/Chicago"),
        ("ATL", "Atlanta", "America/New_York"),
        ("BDA", "Bermuda", "Atlantic/Bermuda"),
        ("BNA", "Nashville", "America/Chicago"),
        ("BWI", "Baltimore", "America/New_York"),
        ("BLR", "Bangalore", "Asia/Kolkata"),
        ("DEN", "Denver", "America/Denver"),
        ("LAS", "Las Vegas", "America/Los_Angeles"),
        ("SFO", "San Francisco", "America/Los_Angeles"),
        ("SAN", "San Diego", "America/Los_Angeles"),
        ("SEA", "Seattle", "America/Los_Angeles"),
        ("MIA", "Miami", "America/New_York"),
        ("MRU", "Mauritius", "Indian/Mauritius"),
        ("BOS", "Boston", "America/New_York"),
        ("CDG", "Paris Charles de Gaulle", "Europe/Paris"),
        ("CVG", "Cincinnati", "America/New_York"),
        ("FRA", "Frankfurt", "Europe/Berlin"),
        ("AMS", "Amsterdam", "Europe/Amsterdam"),
        ("GIG", "Rio de Janeiro", "America/Sao_Paulo"),
        ("MAD", "Madrid", "Europe/Madrid"),
        ("BCN", "Barcelona", "Europe/Madrid"),
        ("BES", "Brest", "Europe/Paris"),
        ("BIO", "Bilbao", "Europe/Madrid"),
        ("BOD", "Bordeaux", "Europe/Paris"),
        ("BVA", "Beauvais", "Europe/Paris"),
        ("CUN", "Cancun", "America/Cancun"),
        ("FCO", "Rome", "Europe/Rome"),
        ("FMM", "Memmingen", "Europe/Berlin"),
        ("FMO", "Münster", "Europe/Berlin"),
        ("FSC", "Figari", "Europe/Paris"),
        ("MXP", "Milan", "Europe/Rome"),
        ("ZRH", "Zurich", "Europe/Zurich"),
        ("VIE", "Vienna", "Europe/Vienna"),
        ("CPH", "Copenhagen", "Europe/Copenhagen"),
        ("CRL", "Charleroi", "Europe/Brussels"),
        ("CWL", "Cardiff", "Europe/London"),
        ("ARN", "Stockholm", "Europe/Stockholm"),
        ("OSL", "Oslo", "Europe/Oslo"),
        ("HEL", "Helsinki", "Europe/Helsinki"),
        ("HYD", "Hyderabad", "Asia/Kolkata"),
        ("HHN", "Frankfurt Hahn", "Europe/Berlin"),
        ("HAM", "Hamburg", "Europe/Berlin"),
        ("WAW", "Warsaw", "Europe/Warsaw"),
        ("PRG", "Prague", "Europe/Prague"),
        ("BUD", "Budapest", "Europe/Budapest"),
        ("BRQ", "Brno", "Europe/Prague"),
        ("BTS", "Bratislava", "Europe/Bratislava"),
        ("ATH", "Athens", "Europe/Athens"),
        ("POS", "Port of Spain", "America/Port_of_Spain"),
        ("IST", "Istanbul", "Europe/Istanbul"),
        ("JSI", "Skiathos", "Europe/Athens"),
        ("JTR", "Santorini", "Europe/Athens"),
        ("JED", "Jeddah", "Asia/Riyadh"),
        ("DXB", "Dubai", "Asia/Dubai"),
        ("DOH", "Doha", "Asia/Qatar"),
        ("DUS", "Düsseldorf", "Europe/Berlin"),
        ("EIN", "Eindhoven", "Europe/Amsterdam"),
        ("IAD", "Washington Dulles", "America/New_York"),
        ("AUH", "Abu Dhabi", "Asia/Dubai"),
        ("BKK", "Bangkok", "Asia/Bangkok"),
        ("KUL", "Kuala Lumpur", "Asia/Kuala_Lumpur"),
        ("SIN", "Singapore", "Asia/Singapore"),
        ("HKG", "Hong Kong", "Asia/Hong_Kong"),
        ("KGS", "Kos", "Europe/Athens"),
        ("KSC", "Košice", "Europe/Bratislava"),
        ("NRT", "Tokyo Narita", "Asia/Tokyo"),
        ("HND", "Tokyo Haneda", "Asia/Tokyo"),
        ("ICN", "Seoul Incheon", "Asia/Seoul"),
        ("ISB", "Islamabad", "Asia/Karachi"),
        ("KUN", "Kaunas", "Europe/Vilnius"),
        ("LJU", "Ljubljana", "Europe/Ljubljana"),
        ("SYD", "Sydney", "Australia/Sydney"),
        ("MEL", "Melbourne", "Australia/Melbourne"),
        ("MEX", "Mexico City", "America/Mexico_City"),
        ("MLE", "Maldives", "Indian/Maldives"),
        ("MBX", "Maribor", "Europe/Ljubljana"),
        ("MRS", "Marseille", "Europe/Paris"),
        ("MSY", "New Orleans", "America/Chicago"),
        ("MAA", "Chennai", "Asia/Kolkata"),
        ("BNE", "Brisbane", "Australia/Brisbane"),
        ("PER", "Perth", "Australia/Perth"),
        ("NCE", "Nice", "Europe/Paris"),
        ("NRN", "Weeze", "Europe/Berlin"),
        ("NUE", "Nuremberg", "Europe/Berlin"),
        ("ORY", "Paris Orly", "Europe/Paris"),
        ("OSR", "Ostrava", "Europe/Prague"),
        ("PDX", "Portland", "America/Los_Angeles"),
        ("PHL", "Philadelphia", "America/New_York"),
        ("PHX", "Phoenix", "America/Phoenix"),
        ("PIT", "Pittsburgh", "America/New_York"),
        ("AKL", "Auckland", "Pacific/Auckland"),
        ("YVR", "Vancouver", "America/Vancouver"),
        ("PGF", "Perpignan", "Europe/Paris"),
        ("PMI", "Palma de Mallorca", "Europe/Madrid"),
        ("PMO", "Palermo", "Europe/Rome"),
        ("PSA", "Pisa", "Europe/Rome"),
        ("DEL", "Delhi", "Asia/Kolkata"),
        ("YYZ", "Toronto", "America/Toronto"),
        ("YUL", "Montreal", "America/Toronto"),
        ("YYC", "Calgary", "America/Edmonton"),
        ("PUF", "Pau", "Europe/Paris"),
        ("RNS", "Rennes", "Europe/Paris"),
        ("YEG", "Edmonton", "America/Edmonton"),
        ("LOS", "Lagos", "Africa/Lagos"),
        ("RZE", "Rzeszów", "Europe/Warsaw"),
        ("SKG", "Thessaloniki", "Europe/Athens"),
        ("TPA", "Tampa", "America/New_York"),
        ("YOW", "Ottawa", "America/Toronto"),
        ("SKP", "Skopje", "Europe/Skopje"),
        ("SOF", "Sofia", "Europe/Sofia"),
        ("YHZ", "Halifax", "America/Halifax"),
        ("YWG", "Winnipeg", "America/Edmonton"),
        ("SPU", "Split", "Europe/Zagreb"),
        ("STR", "Stuttgart", "Europe/Berlin"),
        ("SUF", "Lamezia Terme", "Europe/Rome"),
        ("SVG", "Stavanger", "Europe/Oslo"),
        ("TAT", "Poprad", "Europe/Bratislava"),
        ("TFN", "Tenerife North", "Atlantic/Canary"),
        ("TOS", "Tromsø", "Europe/Oslo"),
        ("TPS", "Trapani", "Europe/Rome"),
        ("TUF", "Tours", "Europe/Paris"),
        ("VCE", "Venice", "Europe/Rome"),
        ("VLC", "Valencia", "Europe/Madrid"),
        ("VNO", "Vilnius", "Europe/Vilnius"),
        ("WRO", "Wrocław", "Europe/Warsaw"),
        ("XCR", "Châlons-en-Champagne", "Europe/Paris"),
        ("ZAD", "Zadar", "Europe/Zagreb"),
        ("ZAG", "Zagreb", "Europe/Zagreb")
    ]
    
    // Common airlines
    static let airlines: [(String, String)] = [
        ("BA", "British Airways"),
        ("VS", "Virgin Atlantic"),
        ("EI", "Aer Lingus"),
        ("AF", "Air France"),
        ("LH", "Lufthansa"),
        ("KL", "KLM Royal Dutch Airlines"),
        ("IB", "Iberia"),
        ("AZ", "Alitalia"),
        ("LX", "Swiss International Air Lines"),
        ("OS", "Austrian Airlines"),
        ("SK", "SAS Scandinavian Airlines"),
        ("AY", "Finnair"),
        ("LO", "LOT Polish Airlines"),
        ("OK", "Czech Airlines"),
        ("MA", "Malev Hungarian Airlines"),
        ("OA", "Olympic Air"),
        ("TK", "Turkish Airlines"),
        ("EK", "Emirates"),
        ("QR", "Qatar Airways"),
        ("EY", "Etihad Airways"),
        ("TG", "Thai Airways"),
        ("SQ", "Singapore Airlines"),
        ("CX", "Cathay Pacific"),
        ("NH", "All Nippon Airways"),
        ("JL", "Japan Airlines"),
        ("KE", "Korean Air"),
        ("QF", "Qantas"),
        ("AC", "Air Canada"),
        ("AA", "American Airlines"),
        ("UA", "United Airlines"),
        ("DL", "Delta Air Lines"),
        ("WN", "Southwest Airlines"),
        ("B6", "JetBlue Airways"),
        ("AS", "Alaska Airlines"),
        ("F9", "Frontier Airlines"),
        ("NK", "Spirit Airlines"),
        ("HA", "Hawaiian Airlines")
    ]
}
