//
//  AirportsAndAirlines.swift
//  UK FTL Calc
//
//  Created by Adam Da Costa on 03/08/2025.
//

import Foundation

// MARK: - Airport Data
struct AirportsAndAirlines {
    // Common airport codes with time zones
    static let airports: [(String, String, String)] = [
        ("LHR", "London Heathrow", "Europe/London"),
        ("LGW", "London Gatwick", "Europe/London"),
        ("STN", "London Stansted", "Europe/London"),
        ("DUB", "Dublin", "Europe/Dublin"),
        ("ORK", "Cork", "Europe/Dublin"),
        ("SNN", "Shannon", "Europe/Dublin"),
        ("NOC", "Knock", "Europe/Dublin"),
        ("LTN", "London Luton", "Europe/London"),
        ("SEN", "London Southend", "Europe/London"),
        ("MAN", "Manchester", "Europe/London"),
        ("BRS", "Bristol", "Europe/London"),
        ("EDI", "Edinburgh", "Europe/London"),
        ("BFS", "Belfast International", "Europe/London"),
        ("GLA", "Glasgow", "Europe/London"),
        ("NCL", "Newcastle", "Europe/London"),
        ("BHX", "Birmingham", "Europe/London"),
        ("EMA", "East Midlands", "Europe/London"),
        ("CWL", "Cardiff", "Europe/London"),
        ("SOU", "Southampton", "Europe/London"),
        ("EXT", "Exeter", "Europe/London"),
        ("MME", "Teesside", "Europe/London"),
        ("DSA", "Doncaster Sheffield", "Europe/London"),
        ("BOH", "Bournemouth", "Europe/London"),
        ("ABZ", "Aberdeen", "Europe/London"),
        ("INV", "Inverness", "Europe/London"),
        ("JFK", "New York JFK", "America/New_York"),
        ("LAX", "Los Angeles", "America/Los_Angeles"),
        ("ORD", "Chicago O'Hare", "America/Chicago"),
        ("DFW", "Dallas/Fort Worth", "America/Chicago"),
        ("ATL", "Atlanta", "America/New_York"),
        ("BDA", "Bermuda", "Atlantic/Bermuda"),
        ("BNA", "Nashville", "America/Chicago"),
        ("BWI", "Baltimore", "America/New_York"),
        ("BLR", "Bangalore", "Asia/Kolkata"),
        ("DEN", "Denver", "America/Denver"),
        ("LAS", "Las Vegas", "America/Los_Angeles"),
        ("SFO", "San Francisco", "America/Los_Angeles"),
        ("SAN", "San Diego", "America/Los_Angeles"),
        ("SEA", "Seattle", "America/Los_Angeles"),
        ("MIA", "Miami", "America/New_York"),
        ("MRU", "Mauritius", "Indian/Mauritius"),
        ("BOS", "Boston", "America/New_York"),
        ("CDG", "Paris Charles de Gaulle", "Europe/Paris"),
        ("ORY", "Paris Orly", "Europe/Paris"),
        ("LYS", "Lyon", "Europe/Paris"),
        ("NCE", "Nice Côte d'Azur", "Europe/Paris"),
        ("BOD", "Bordeaux", "Europe/Paris"),
        ("MRS", "Marseille", "Europe/Paris"),
        ("TLS", "Toulouse", "Europe/Paris"),
        ("CVG", "Cincinnati", "America/New_York"),
        ("FRA", "Frankfurt", "Europe/Berlin"),
        ("BER", "Berlin Brandenburg", "Europe/Berlin"),
        ("HAM", "Hamburg", "Europe/Berlin"),
        ("DUS", "Düsseldorf", "Europe/Berlin"),
        ("MUC", "Munich", "Europe/Berlin"),
        ("STR", "Stuttgart", "Europe/Berlin"),
        ("CGN", "Cologne", "Europe/Berlin"),
        ("NUE", "Nuremberg", "Europe/Berlin"),
        ("AMS", "Amsterdam", "Europe/Amsterdam"),
        ("GIG", "Rio de Janeiro", "America/Sao_Paulo"),
        ("GRU", "São Paulo", "America/Sao_Paulo"),
        ("EZE", "Buenos Aires", "America/Argentina/Buenos_Aires"),
        ("BOG", "Bogotá", "America/Bogota"),
        ("LIM", "Lima", "America/Lima"),
        ("SCL", "Santiago", "America/Santiago"),
        ("MAD", "Madrid", "Europe/Madrid"),
        ("BCN", "Barcelona", "Europe/Madrid"),
        ("PMI", "Palma de Mallorca", "Europe/Madrid"),
        ("ALC", "Alicante", "Europe/Madrid"),
        ("AGP", "Málaga", "Europe/Madrid"),
        ("IBZ", "Ibiza", "Europe/Madrid"),
        ("BIO", "Bilbao", "Europe/Madrid"),
        ("VLC", "Valencia", "Europe/Madrid"),
        ("SVQ", "Seville", "Europe/Madrid"),
        ("XRY", "Jerez", "Europe/Madrid"),
        ("CDT", "Castellón", "Europe/Madrid"),
        ("BES", "Brest", "Europe/Paris"),
        ("AGP", "Agadir", "Africa/Casablanca"),
        ("FEZ", "Fez", "Africa/Casablanca"),
        ("RAK", "Marrakech", "Africa/Casablanca"),
        ("CMN", "Casablanca", "Africa/Casablanca"),
        ("TUN", "Tunis", "Africa/Tunis"),
        ("BIO", "Bilbao", "Europe/Madrid"),
        ("BOD", "Bordeaux", "Europe/Paris"),
        ("BVA", "Beauvais", "Europe/Paris"),
        ("BIQ", "Biarritz", "Europe/Paris"),
        ("DOL", "Deauville", "Europe/Paris"),
        ("CUN", "Cancun", "America/Cancun"),
        ("ANU", "Antigua", "America/Antigua"),
        ("BGI", "Barbados", "America/Barbados"),
        ("GND", "Grenada", "America/Grenada"),
        ("POS", "Port of Spain", "America/Port_of_Spain"),
        ("FCO", "Rome", "Europe/Rome"),
        ("MXP", "Milan Malpensa", "Europe/Rome"),
        ("NAP", "Naples International", "Europe/Rome"),
        ("VCE", "Venice Marco Polo", "Europe/Rome"),
        ("PSA", "Pisa", "Europe/Rome"),
        ("PMO", "Palermo", "Europe/Rome"),
        ("BRI", "Bari", "Europe/Rome"),
        ("CTA", "Catania", "Europe/Rome"),
        ("FMM", "Memmingen", "Europe/Berlin"),
        ("FMO", "Münster", "Europe/Berlin"),
        ("FSC", "Figari", "Europe/Paris"),
        ("MXP", "Milan Malpensa", "Europe/Rome"),
        ("LIN", "Milan Linate", "Europe/Rome"),
        ("BGY", "Milan Bergamo", "Europe/Rome"),
        ("AHO", "Alghero", "Europe/Rome"),
        ("PSR", "Pescara", "Europe/Rome"),
        ("AOI", "Ancona", "Europe/Rome"),
        ("ZRH", "Zurich", "Europe/Zurich"),
        ("GVA", "Geneva", "Europe/Zurich"),
        ("BSL", "Basel Mulhouse", "Europe/Zurich"),
        ("VIE", "Vienna", "Europe/Vienna"),
        ("INN", "Innsbruck", "Europe/Vienna"),
        ("SZG", "Salzburg", "Europe/Vienna"),
        ("CPH", "Copenhagen", "Europe/Copenhagen"),
        ("CRL", "Charleroi", "Europe/Brussels"),
        ("BRU", "Brussels", "Europe/Brussels"),
        ("LUX", "Luxembourg", "Europe/Luxembourg"),
        ("BRN", "Bern", "Europe/Zurich"),
        ("CWL", "Cardiff", "Europe/London"),
        ("ARN", "Stockholm Arlanda", "Europe/Stockholm"),
        ("GOT", "Gothenburg", "Europe/Stockholm"),
        ("OSL", "Oslo", "Europe/Oslo"),
        ("TRD", "Trondheim", "Europe/Oslo"),
        ("BOO", "Bodø", "Europe/Oslo"),
        ("HEL", "Helsinki", "Europe/Helsinki"),
        ("HYD", "Hyderabad", "Asia/Kolkata"),
        ("BOM", "Mumbai", "Asia/Kolkata"),
        ("DEL", "Delhi", "Asia/Kolkata"),
        ("BLR", "Bangalore", "Asia/Kolkata"),
        ("CCU", "Kolkata", "Asia/Kolkata"),
        ("BKK", "Bangkok", "Asia/Bangkok"),
        ("KUL", "Kuala Lumpur", "Asia/Kuala_Lumpur"),
        ("SIN", "Singapore", "Asia/Singapore"),
        ("HKG", "Hong Kong", "Asia/Hong_Kong"),
        ("ICN", "Seoul Incheon", "Asia/Seoul"),
        ("NRT", "Tokyo Narita", "Asia/Tokyo"),
        ("HND", "Tokyo Haneda", "Asia/Tokyo"),
        ("KIX", "Osaka Kansai", "Asia/Tokyo"),
        ("HHN", "Frankfurt Hahn", "Europe/Berlin"),
        ("HAM", "Hamburg", "Europe/Berlin"),
        ("WAW", "Warsaw", "Europe/Warsaw"),
        ("KRK", "Kraków", "Europe/Warsaw"),
        ("WRO", "Wrocław", "Europe/Warsaw"),
        ("PRG", "Prague", "Europe/Prague"),
        ("BUD", "Budapest", "Europe/Budapest"),
        ("SOF", "Sofia", "Europe/Sofia"),
        ("BOJ", "Burgas", "Europe/Sofia"),
        ("VAR", "Varna", "Europe/Sofia"),
        ("BRQ", "Brno", "Europe/Prague"),
        ("BTS", "Bratislava", "Europe/Bratislava"),
        ("ATH", "Athens", "Europe/Athens"),
        ("JSI", "Skiathos", "Europe/Athens"),
        ("JTR", "Santorini", "Europe/Athens"),
        ("KGS", "Kos", "Europe/Athens"),
        ("RHO", "Rhodes", "Europe/Athens"),
        ("HER", "Heraklion", "Europe/Athens"),
        ("CHQ", "Chania", "Europe/Athens"),
        ("POS", "Port of Spain", "America/Port_of_Spain"),
        ("IST", "Istanbul", "Europe/Istanbul"),
        ("JSI", "Skiathos", "Europe/Athens"),
        ("JTR", "Santorini", "Europe/Athens"),
        ("JED", "Jeddah", "Asia/Riyadh"),
        ("RUH", "Riyadh", "Asia/Riyadh"),
        ("DXB", "Dubai", "Asia/Dubai"),
        ("DOH", "Doha", "Asia/Qatar"),
        ("AUH", "Abu Dhabi", "Asia/Dubai"),
        ("BEY", "Beirut", "Asia/Beirut"),
        ("DUS", "Düsseldorf", "Europe/Berlin"),
        ("EIN", "Eindhoven", "Europe/Amsterdam"),
        ("IAD", "Washington Dulles", "America/New_York"),
        ("AUH", "Abu Dhabi", "Asia/Dubai"),
        ("BKK", "Bangkok", "Asia/Bangkok"),
        ("KUL", "Kuala Lumpur", "Asia/Kuala_Lumpur"),
        ("SIN", "Singapore", "Asia/Singapore"),
        ("HKG", "Hong Kong", "Asia/Hong_Kong"),
        ("KGS", "Kos", "Europe/Athens"),
        ("KSC", "Košice", "Europe/Bratislava"),
        ("NRT", "Tokyo Narita", "Asia/Tokyo"),
        ("HND", "Tokyo Haneda", "Asia/Tokyo"),
        ("ICN", "Seoul Incheon", "Asia/Seoul"),
        ("ISB", "Islamabad", "Asia/Karachi"),
        ("KUN", "Kaunas", "Europe/Vilnius"),
        ("LJU", "Ljubljana", "Europe/Ljubljana"),
        ("SYD", "Sydney", "Australia/Sydney"),
        ("MEL", "Melbourne", "Australia/Melbourne"),
        ("MEX", "Mexico City", "America/Mexico_City"),
        ("MLE", "Maldives", "Indian/Maldives"),
        ("MBX", "Maribor", "Europe/Ljubljana"),
        ("MRS", "Marseille", "Europe/Paris"),
        ("MSY", "New Orleans", "America/Chicago"),
        ("MAA", "Chennai", "Asia/Kolkata"),
        ("BNE", "Brisbane", "Australia/Brisbane"),
        ("PER", "Perth", "Australia/Perth"),
        ("NCE", "Nice", "Europe/Paris"),
        ("NRN", "Weeze", "Europe/Berlin"),
        ("NUE", "Nuremberg", "Europe/Berlin"),
        ("ORY", "Paris Orly", "Europe/Paris"),
        ("OSR", "Ostrava", "Europe/Prague"),
        ("PDX", "Portland", "America/Los_Angeles"),
        ("PHL", "Philadelphia", "America/New_York"),
        ("PHX", "Phoenix", "America/Phoenix"),
        ("PIT", "Pittsburgh", "America/New_York"),
        ("AKL", "Auckland", "Pacific/Auckland"),
        ("YVR", "Vancouver", "America/Vancouver"),
        ("PGF", "Perpignan", "Europe/Paris"),
        ("PMI", "Palma de Mallorca", "Europe/Madrid"),
        ("PMO", "Palermo", "Europe/Rome"),
        ("PSA", "Pisa", "Europe/Rome"),
        ("DEL", "Delhi", "Asia/Kolkata"),
        ("YYZ", "Toronto", "America/Toronto"),
        ("YUL", "Montreal", "America/Toronto"),
        ("YYC", "Calgary", "America/Edmonton"),
        ("YOW", "Ottawa", "America/Toronto"),
        ("YHZ", "Halifax", "America/Halifax"),
        ("YWG", "Winnipeg", "America/Edmonton"),
        ("PUF", "Pau", "Europe/Paris"),
        ("RNS", "Rennes", "Europe/Paris"),
        ("YEG", "Edmonton", "America/Edmonton"),
        ("LOS", "Lagos", "Africa/Lagos"),
        ("ALG", "Algiers", "Africa/Algiers"),
        ("CAI", "Cairo", "Africa/Cairo"),
        ("JNB", "Johannesburg", "Africa/Johannesburg"),
        ("CPT", "Cape Town", "Africa/Johannesburg"),
        ("NBO", "Nairobi", "Africa/Nairobi"),
        ("ACC", "Accra", "Africa/Accra"),
        ("DAR", "Dar es Salaam", "Africa/Dar_es_Salaam"),
        ("LUN", "Lusaka", "Africa/Lusaka"),
        ("HRE", "Harare", "Africa/Harare"),
        ("RZE", "Rzeszów", "Europe/Warsaw"),
        ("SKG", "Thessaloniki", "Europe/Athens"),
        ("TPA", "Tampa", "America/New_York"),
        ("MCO", "Orlando", "America/New_York"),
        ("MIA", "Miami", "America/New_York"),
        ("KIN", "Kingston", "America/Jamaica"),
        ("SVD", "St Vincent", "America/St_Vincent"),
        ("MLE", "Malé", "Indian/Maldives"),
        ("YOW", "Ottawa", "America/Toronto"),
        ("SKP", "Skopje", "Europe/Skopje"),
        ("SOF", "Sofia", "Europe/Sofia"),
        ("YHZ", "Halifax", "America/Halifax"),
        ("YWG", "Winnipeg", "America/Edmonton"),
        ("SPU", "Split", "Europe/Zagreb"),
        ("DBV", "Dubrovnik", "Europe/Zagreb"),
        ("PUY", "Pula", "Europe/Zagreb"),
        ("ZAD", "Zadar", "Europe/Zagreb"),
        ("RJK", "Rijeka", "Europe/Zagreb"),
        ("STR", "Stuttgart", "Europe/Berlin"),
        ("SUF", "Lamezia Terme", "Europe/Rome"),
        ("SVG", "Stavanger", "Europe/Oslo"),
        ("TAT", "Poprad", "Europe/Bratislava"),
        ("TFN", "Tenerife North", "Atlantic/Canary"),
        ("TFS", "Tenerife South", "Atlantic/Canary"),
        ("LPA", "Gran Canaria", "Atlantic/Canary"),
        ("FUE", "Fuerteventura", "Atlantic/Canary"),
        ("ACE", "Lanzarote", "Atlantic/Canary"),
        ("FNC", "Funchal", "Atlantic/Madeira"),
        ("PXO", "Porto Santo", "Atlantic/Madeira"),
        ("LIS", "Lisbon", "Europe/Lisbon"),
        ("OPO", "Porto", "Europe/Lisbon"),
        ("FAR", "Faro", "Europe/Lisbon"),
        ("TOS", "Tromsø", "Europe/Oslo"),
        ("TPS", "Trapani", "Europe/Rome"),
        ("TUF", "Tours", "Europe/Paris"),
        ("VCE", "Venice", "Europe/Rome"),
        ("VLC", "Valencia", "Europe/Madrid"),
        ("VNO", "Vilnius", "Europe/Vilnius"),
        ("WRO", "Wrocław", "Europe/Warsaw"),
        ("XCR", "Châlons-en-Champagne", "Europe/Paris"),
        ("ZAD", "Zadar", "Europe/Zagreb"),
        ("ZAG", "Zagreb", "Europe/Zagreb"),
        ("TIA", "Tirana", "Europe/Tirana"),
        ("SID", "Sal", "Atlantic/Cape_Verde"),
        ("AMM", "Amman", "Asia/Amman"),
        ("AQJ", "Aqaba", "Asia/Amman"),
        ("SSH", "Sharm El Sheikh", "Africa/Cairo"),
        ("HRG", "Hurghada", "Africa/Cairo"),
        ("LCA", "Larnaca", "Asia/Nicosia"),
        ("PFO", "Paphos", "Asia/Nicosia"),
        ("TLV", "Tel Aviv", "Asia/Jerusalem"),
        ("KTT", "Kittilä", "Europe/Helsinki"),
        ("LIS", "Lisbon", "Europe/Lisbon"),
        ("OPO", "Porto", "Europe/Lisbon"),
        ("FAR", "Faro", "Europe/Lisbon"),
        ("FNC", "Funchal", "Atlantic/Madeira"),
        ("PXO", "Porto Santo", "Atlantic/Madeira"),
        ("AMM", "Amman", "Asia/Amman"),
        ("AQJ", "Aqaba", "Asia/Amman"),
        ("SSH", "Sharm El Sheikh", "Africa/Cairo"),
        ("HRG", "Hurghada", "Africa/Cairo"),
        ("LCA", "Larnaca", "Asia/Nicosia"),
        ("PFO", "Paphos", "Asia/Nicosia"),
        ("TLV", "Tel Aviv", "Asia/Jerusalem"),
        ("KTT", "Kittilä", "Europe/Helsinki"),
        ("ROV", "Rostov", "Europe/Moscow"),
        ("LED", "St Petersburg", "Europe/Moscow"),
        ("KZN", "Kazan", "Europe/Moscow"),
        ("UFA", "Ufa", "Asia/Yekaterinburg"),
        ("SVX", "Yekaterinburg", "Asia/Yekaterinburg"),
        ("KRR", "Krasnodar", "Europe/Moscow"),
        ("AER", "Sochi", "Europe/Moscow"),
        ("VOG", "Volgograd", "Europe/Moscow"),
        ("ASF", "Astrakhan", "Europe/Moscow"),
        ("GOJ", "Nizhny Novgorod", "Europe/Moscow"),
        ("KUF", "Samara", "Europe/Samara"),
        ("VVO", "Vladivostok", "Asia/Vladivostok"),
        ("IKT", "Irkutsk", "Asia/Irkutsk"),
        ("OVB", "Novosibirsk", "Asia/Novosibirsk"),
        ("KJA", "Krasnoyarsk", "Asia/Krasnoyarsk"),
        ("UUS", "Yuzhno-Sakhalinsk", "Asia/Sakhalin"),
        ("LAP", "Lapland", "Europe/Helsinki"),
        ("TMP", "Tampere", "Europe/Helsinki"),
        ("LPP", "Lappeenranta", "Europe/Helsinki"),
        ("TLL", "Tallinn", "Europe/Tallinn"),
        ("RIX", "Riga", "Europe/Riga"),
        ("VNO", "Vilnius", "Europe/Vilnius"),
        ("GDN", "Gdańsk", "Europe/Warsaw"),
        ("POZ", "Poznań", "Europe/Warsaw"),
        ("KTW", "Katowice", "Europe/Warsaw"),
        ("WRO", "Wrocław", "Europe/Warsaw"),
        ("KRK", "Kraków", "Europe/Warsaw"),
        ("WAW", "Warsaw", "Europe/Warsaw"),
        ("BTS", "Bratislava", "Europe/Bratislava"),
        ("KSC", "Košice", "Europe/Bratislava"),
        ("BUD", "Budapest", "Europe/Budapest"),
        ("DEB", "Debrecen", "Europe/Budapest"),
        ("SOF", "Sofia", "Europe/Sofia"),
        ("BOJ", "Burgas", "Europe/Sofia"),
        ("VAR", "Varna", "Europe/Sofia"),
        ("OTP", "Bucharest", "Europe/Bucharest"),
        ("CLJ", "Cluj-Napoca", "Europe/Bucharest"),
        ("TSR", "Timișoara", "Europe/Bucharest"),
        ("ZAG", "Zagreb", "Europe/Zagreb"),
        ("SPU", "Split", "Europe/Zagreb"),
        ("DBV", "Dubrovnik", "Europe/Zagreb"),
        ("PUY", "Pula", "Europe/Zagreb"),
        ("ZAD", "Zadar", "Europe/Zagreb"),
        ("RJK", "Rijeka", "Europe/Zagreb"),
        ("OSI", "Osijek", "Europe/Zagreb"),
        ("LJU", "Ljubljana", "Europe/Ljubljana"),
        ("MBX", "Maribor", "Europe/Ljubljana"),
        ("TIA", "Tirana", "Europe/Tirana"),
        ("SKP", "Skopje", "Europe/Skopje"),
        ("SOF", "Sofia", "Europe/Sofia"),
        ("ATH", "Athens", "Europe/Athens"),
        ("HER", "Heraklion", "Europe/Athens"),
        ("CHQ", "Chania", "Europe/Athens"),
        ("RHO", "Rhodes", "Europe/Athens"),
        ("JSI", "Skiathos", "Europe/Athens"),
        ("JTR", "Santorini", "Europe/Athens"),
        ("KGS", "Kos", "Europe/Athens"),
        ("KVA", "Kavala", "Europe/Athens"),
        ("LRA", "Larissa", "Europe/Athens"),
        ("VOL", "Volos", "Europe/Athens"),
        ("IOA", "Ioannina", "Europe/Athens"),
        ("AXD", "Alexandroupolis", "Europe/Athens"),
        ("KGS", "Kos", "Europe/Athens"),
        ("JSI", "Skiathos", "Europe/Athens"),
        ("JTR", "Santorini", "Europe/Athens"),
        ("RHO", "Rhodes", "Europe/Athens"),
        ("HER", "Heraklion", "Europe/Athens"),
        ("CHQ", "Chania", "Europe/Athens"),
        ("KVA", "Kavala", "Europe/Athens"),
        ("LRA", "Larissa", "Europe/Athens"),
        ("VOL", "Volos", "Europe/Athens"),
        ("IOA", "Ioannina", "Europe/Athens"),
        ("AXD", "Alexandroupolis", "Europe/Athens"),
        ("BLL", "Billund", "Europe/Copenhagen"),
        ("AAL", "Aalborg", "Europe/Copenhagen"),
        ("CPH", "Copenhagen", "Europe/Copenhagen"),
        ("GOT", "Gothenburg", "Europe/Stockholm"),
        ("MMX", "Malmö", "Europe/Stockholm"),
        ("VBY", "Visby", "Europe/Stockholm"),
        ("TRF", "Oslo Torp", "Europe/Oslo"),
        ("BGO", "Bergen", "Europe/Oslo"),
        ("SVG", "Stavanger", "Europe/Oslo"),
        ("TOS", "Tromsø", "Europe/Oslo"),
        ("BOO", "Bodø", "Europe/Oslo"),
        ("TLL", "Tallinn", "Europe/Tallinn"),
        ("TKU", "Turku", "Europe/Helsinki"),
        ("RVN", "Rovaniemi", "Europe/Helsinki"),
        ("KTT", "Kittilä", "Europe/Helsinki"),
        ("LAP", "Lapland", "Europe/Helsinki"),
        ("TMP", "Tampere", "Europe/Helsinki"),
        ("LPP", "Lappeenranta", "Europe/Helsinki")
    ]
    
    // UK Airlines
    static let airlines: [(String, String)] = [
        ("BA", "British Airways"),
        ("VS", "Virgin Atlantic"),
        ("U2", "EasyJet"),
        ("LS", "Jet2"),
        ("FR", "Ryanair")
    ]
}
